import React from 'react';
import { Link } from 'react-router-dom';
import { Brain, Play, Info, Cpu, ArrowRight, Code2, Users } from 'lucide-react';
import { motion } from 'framer-motion';

export default function Home() {
  return (
    <div style={{ minHeight: 'calc(100vh - 80px)', paddingBottom: '40px' }}>
      {/* Hero Section */}
      <section style={{
        maxWidth: '1300px',
        margin: '0 auto',
        padding: '70px 24px 40px',
        textAlign: 'center',
        position: 'relative'
      }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="badge-ai" style={{ marginBottom: '20px', padding: '6px 16px', fontSize: '0.85rem' }}>
            <Cpu size={16} /> Final Year Engineering Project Showcase
          </div>

          <h1 style={{
            fontSize: 'clamp(2.5rem, 5vw, 4rem)',
            lineHeight: 1.1,
            marginBottom: '20px',
            background: 'linear-gradient(135deg, #ffffff 0%, #cbd5e1 50%, var(--accent-blue) 100%)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            maxWidth: '920px',
            margin: '0 auto 20px'
          }}>
            AI-Powered Chess Move Recommendation System
          </h1>

          <p style={{
            fontSize: '1.2rem',
            color: 'var(--text-muted)',
            maxWidth: '760px',
            margin: '0 auto 36px',
            lineHeight: 1.6
          }}>
            A clean, presentation-friendly platform where two human players compete head-to-head while receiving real-time legal move recommendations generated by a trained TensorFlow Convolutional Neural Network.
          </p>

          {/* Main Call-to-Action Buttons */}
          <div style={{ display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link to="/game" style={{ textDecoration: 'none' }}>
              <button className="btn-primary" style={{ padding: '16px 36px', fontSize: '1.1rem' }}>
                <Play size={20} /> Launch Play Arena <ArrowRight size={18} />
              </button>
            </Link>

            <Link to="/about" style={{ textDecoration: 'none' }}>
              <button className="btn-secondary" style={{ padding: '16px 32px', fontSize: '1.1rem' }}>
                <Info size={20} /> Project Documentation
              </button>
            </Link>
          </div>
        </motion.div>
      </section>

      {/* Engineering Architecture Feature Cards */}
      <section style={{ maxWidth: '1300px', margin: '20px auto 0', padding: '0 24px' }}>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: '24px'
        }}>
          <motion.div
            whileHover={{ y: -6 }}
            className="glass-panel"
            style={{ padding: '32px' }}
          >
            <div style={{
              width: '48px',
              height: '48px',
              borderRadius: '12px',
              background: 'linear-gradient(135deg, var(--accent-blue), var(--accent-purple))',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              marginBottom: '20px',
              boxShadow: 'var(--shadow-glow-blue)'
            }}>
              <Users size={24} color="#ffffff" />
            </div>
            <h3 style={{ fontSize: '1.25rem', color: '#ffffff', marginBottom: '10px' }}>
              Player vs Player Match
            </h3>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', lineHeight: 1.6 }}>
              Human Player 1 (White) and Player 2 (Black) control piece movements with full legal move validation via Chess.js.
            </p>
          </motion.div>

          <motion.div
            whileHover={{ y: -6 }}
            className="glass-panel"
            style={{ padding: '32px' }}
          >
            <div style={{
              width: '48px',
              height: '48px',
              borderRadius: '12px',
              background: 'linear-gradient(135deg, var(--accent-emerald), #059669)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              marginBottom: '20px',
              boxShadow: 'var(--shadow-glow-emerald)'
            }}>
              <Brain size={24} color="#ffffff" />
            </div>
            <h3 style={{ fontSize: '1.25rem', color: '#ffffff', marginBottom: '10px' }}>
              TensorFlow Move Recommendations
            </h3>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', lineHeight: 1.6 }}>
              Queries the Flask REST server for top legal move recommendations evaluated by a Convolutional Neural Network.
            </p>
          </motion.div>

          <motion.div
            whileHover={{ y: -6 }}
            className="glass-panel"
            style={{ padding: '32px' }}
          >
            <div style={{
              width: '48px',
              height: '48px',
              borderRadius: '12px',
              background: 'linear-gradient(135deg, var(--accent-amber), #d97706)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              marginBottom: '20px'
            }}>
              <Code2 size={24} color="#ffffff" />
            </div>
            <h3 style={{ fontSize: '1.25rem', color: '#ffffff', marginBottom: '10px' }}>
              Decoupled Architecture
            </h3>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', lineHeight: 1.6 }}>
              React 19 Vite client communicates with Python Flask backend via HTTP REST endpoints for maximum scalability.
            </p>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
